### ISSUE TITLE
Check for unique headers

### ISSUE THREAD

**Issue by torognes** [torognes/swarm#10]
Check for unique headers and report error if duplicates are found

**Comment by frederic-mahe** [comment]
That checking is not active anymore, it seems. The command below should return an error, and it does not:
```
echo -e ">a_10\nACGT\n>a_5\nTGCA\n" | swarm
```

**Comment by torognes** [comment]
It includes the abundance info in the string that is checked for uniqueness. The two headers in the example above are therefore considered different. The abundance should be excluded.

**Comment by torognes** [comment]
Sorry, the unique header checking was not working at all. Working on a fix.

**Comment by frederic-mahe** [comment]
implemented in swarm 2.1.13
