### ISSUE TITLE
not all memory is freed when swarm exits with an error

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/swarm#103]
This is a very minor issue.

`valgrind` indicates that some blocks are still reachable when swarm exits after an error (no abundance value in this toy example): 
```sh
printf ">s1\nA\n" | valgrind swarm

# for a full report
printf ">s1\nA\n" | valgrind --leak-check=full --show-leak-kinds=all swarm
```

**Comment by torognes** [comment]
When fatal errors occur the program often terminates without explicitly freeing memory. All memory will be freed automatically afterwards when the program exits. I do not think this should be considered an error.

**Comment by frederic-mahe** [comment]
Agreed.
