### ISSUE TITLE
bug in -w output when using the -a option

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/swarm#106]
The fasta file of cluster representatives (`-w`) is not correct when using the `-a` option to append abundance values to amplicons missing one.
```sh
OUTPUT=$(mktemp)
printf ">s1\nT\n" | swarm -a 1 -w "${OUTPUT}" &> /dev/null
cat "${OUTPUT}"
rm "${OUTPUT}"
```
The identifier of the amplicon (`s1`) is missing, and only the abundance value is reported:
```
>_1
t
```

**Comment by torognes** [comment]
Fixed.
