### ISSUE TITLE
swarm output file

### ISSUE THREAD

**Issue by tilaknayak** [torognes/swarm#118]
I am a new user of swarm, after i run the swarm (code `./swarm -f -t 2 -z -o myfile.txt -w myfile.representatives.fasta amplicons_linearized_dereplicated.fasta myfile.swarms`) i got a file like that
```
P11.496;size=1426; P11.370;size=1162; P11.296;size=1158; P11.418;size=901; P11.1153;size=842; P11.108;size=772; P11.469;size=554; P11.3485;size=331; P11.119;size=130; P11.2464;size=108; P11.5139;size=52; P11.161963;size=39; P11.42759;size=37; P11.22806;size=31; P11.595;size=29; P11.42703;size=27; P11.8313;size=27; P11.7145;size=25; P11.3383;size=24; P11.44670;size=17; P11.57536;size=16; P11.1587;size=14; P11.65743;size=11; P11.57863;size=8; P11.25311;size=7; P11.167457;size=6; P11.66950;size=6; P11.3620;size=5; P11.52385;size=5; P11.76267;size=5; P11.87618;size=5; P11.114824;size=4; P11.11757;size=4; P11.1182;size=4; P11.30876;size=4; P11.4521;size=4; P11.58180;size=4; P11.61547;size=4; P11.63706;size=4; P11.6975;size=4; P11.86352;size=4; P13.19696;size=4; P11.117541;size=3;
```
now my question is is that file is okay because i don't know how output file look and 2nd question from this how i deal with the statistical analysis because i don't understand the otu cluster value and otu number.
kindly reply me.

**Comment by frederic-mahe** [comment]
dear @tilaknayak sorry for the delay in answering you. I took some early vacation this year.

Your `swarm` command seems OK (except you can drop `myfile.swarms`, this is redundant with the `-o` option:
```sh
./swarm \
    -f \
    -t 2 \
    -z \
    -o myfile.txt \
    -w myfile.representatives.fasta \
    amplicons_linearized_dereplicated.fasta
```
The results you obtain seem normal too. `swarm` is a clustering method, it takes fasta sequences and tells you what are the clusters (i.e. the groups of sequences) that make sense. That's all `swarm` does.

After the clustering with `swarm`, there are still a few steps you need to perform before obtaining an OTU table you can analyze with R packages such as vegan or phyloseq. If you are interested, [here is a page](https://github.com/frederic-mahe/swarm/wiki/Fred's-metabarcoding-pipeline) where I describe how I use swarm and other tools for my own research projects.

**Comment by frederic-mahe** [comment]
@tilaknayak I am closing that issue. Feel free to open a new issue if you have another question.

**Comment by tilaknayak** [comment]
Hello sir now I am facing with a different problem. I am trying to build a
contingency table for amplicon with this script (python
amplicon_contingency_table.py P11_dereplicated.fasta > amplicons_table.csv)
and I got an error. Please help me to solve this error. I give the details
of this error bellow.
pkd@pkd-HP-406-G1-MT:~/swarm-master/scripts$ python
amplicon_contingency_table.py P11_dereplicated.fasta > amplicons_table.csv
Traceback (most recent call last):
  File "amplicon_contingency_table.py", line 101, in <module>
    main()
  File "amplicon_contingency_table.py", line 65, in main
    all_amplicons, amplicons2samples, samples = fasta_parse()
  File "amplicon_contingency_table.py", line 41, in fasta_parse
    amplicon, abundance = line.strip(">;\n").split(separator)
ValueError: need more than 1 value to unpack

Thanking you.
From
Tilak Nayak

**Comment by Sankhajit-byte** [comment]
Hello sir, I am the new user of Swarm, after i run the code 
awk -v SWARM="${SWARMS}" -v TABLE="${AMPLICON_TABLE}"  'BEGIN {FS = " "
            while ((getline < SWARM) > 0) {
                swarms[$1] = $0
            }
            FS = "\t"
            while ((getline < TABLE) > 0) {
                table[$1] = $0
            }
           }

     {# Parse the stat file (OTUs sorted by decreasing abundance)
      seed = $3 "_" $4
      n = split(swarms[seed], OTU, "[ _]")
      for (i = 1; i < n; i = i + 2) {
          s = split(table[OTU[i]], abundances, "\t")
          for (j = 1; j < s; j++) {
              samples[j] += abundances[j+1]
          }
      }
      printf "%s\t%s", NR, $3
      for (j = 1; j < s; j++) {
          printf "\t%s", samples[j]
      }
     printf "\n"
     delete samples
     }' "${STATS}" >> "${OTU_TABLE}"
I got a otu contingency table, but this table can't show the common OTU number present in each sample. The table is blank why it is so                                                                                                                                                                                                                                               and my table looks like
OTU amplicon | S-1A1_dereplicated | S-1B1_dereplicated | S-1B3_dereplicated | S-1C1_dereplicated | S-1C2_dereplicated | S-1C3_dereplicated | S-2A2_dereplicated | S-2B1_dereplicated 
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 8f862e5929b63b3ff5b2cac7a900aed9a4204319 |   |   |   |   |   |   |   |   |   |  
2 0c359b9fa339daadc2bca96efe4424dc1a71a0ff |   |   |   |   |   |   |   |   |   |  
3 ec7785f108712d4ce0ebf49d25795b159abc42ff |   |   |   |   |   |   |   |   |   |  
4 71cde4bd6d97a3bc0eb6806e261ced63a606deb5 |   |   |   |   |   |   |   |   |   |  
5 8db38401150d4d98dfeab0af54a05f6c37675cc6 |   |   |   |   |   |   |   |   |   |  
6 6bab60bf4581f948967c420de416dc631ca5f9fd |   |   |   |   |   |   |   |   |   |  
7 8a0f6aa6f4344f48555ef512a14200c60e8af9ec |   |   |   |   |   |   |   |   |   |  
8 144cf0e9072588ca96d98865612889c61871c111 |   |   |   |   |   |   |   |   |   |  
9 ae99f20cda94590827c0149c53f8e239a79b01f6 |   |   |   |   |   |   |   |   |   |  
10 988fa92d9a4f111d22b2321ce97e6f1ee5950067 |   |   |   |   |   |   |   |   |   |  
11 7f3e92cf74a1064966226faf0c04a2069433dd51 |   |   |   |   |   |   |   |   |   |  
May you please tell me where is the problem. I already have amplicon contingency table, amplicons.swarm and amplicon_stats.txt file
