### ISSUE TITLE
Error occur in amplicon_contingency_table.py

### ISSUE THREAD

**Issue by debjitde01** [torognes/swarm#128]
Hello sir

I am facing a problem, I am trying to build a contingency table for amplicon with this script (`python amplicon_contingency_table.py P11_dereplicated.fasta > amplicons_table.csv`) and I got an error. Please help me to solve this error. I give the details of this error bellow.
```sh
pkd@pkd-HP-406-G1-MT:~/swarm-master/scripts$ python amplicon_contingency_table.py P11_dereplicated.fasta > amplicons_table.csv
Traceback (most recent call last):
  File "amplicon_contingency_table.py", line 101, in <module>
    main()
  File "amplicon_contingency_table.py", line 65, in main
    all_amplicons, amplicons2samples, samples = fasta_parse()
  File "amplicon_contingency_table.py", line 41, in fasta_parse
    amplicon, abundance = line.strip(">;\n").split(separator)
ValueError: need more than 1 value to unpack
```

**Comment by frederic-mahe** [comment]
hello @debjitde01 

there seems to be a problem with you fasta file. Could you please show us a sample of your fasta file? the first few lines should be enough.

**Comment by frederic-mahe** [comment]
@debjitde01 The script `amplicon_contingency_table.py` is expecting abundance values in usearch/vsearch format (`;size=`), whereas your fasta file uses `_` to separate the abundance values. You can either edit your fasta file (`sed -i '/^>/ s/_/;size=/'`), or change the script (`separator = ";size="` should be `separator = "_"`).

But there might be a confusion here, the goal of the script `amplicon_contingency_table.py` is to parse many fasta files at once and to provide a contingency table listing each amplicon and the samples where they occur. That script **does not** produce an OTU contingency table.

If an OTU table if what you are interested in, you might want to follow the pipeline described on this [page](https://github.com/frederic-mahe/swarm/wiki/Fred's-metabarcoding-pipeline).

**Comment by debjitde01** [comment]
Thank you. Now the problem is short out.

**Comment by frederic-mahe** [comment]
Good. I'll close this issue then. Feel free to open a new issue if need be.

**Comment by debjitde01** [comment]
Sure and thank you so much for your help
*Debjit De*

*Research Scholar*
*C/O - Dr. Paltu Kumar Dhal*
*Assistant Professor*
*Department of Life Science & Biotechnology*
*Jadavpur University*
*Kolkata - 700032.*
