### ISSUE TITLE
abundance values generator?

### ISSUE THREAD

**Issue by dcastaneda5** [torognes/swarm#131]
Hi! I was just wondering if the `--derep_fulllength` with the option of `--sizeout `generates the appropriate abundance values required by swarm?

One of my output sequences from this generator is the following:
```
>797d2f73bb1f3a506c560c8ad547cb7cbf74a8a7;size=36
GTATTGACAGGTTATAGTTTATTTCAAAAGGAAAAAATGGTATTAAATGAAGGAACAAGTGGAACAGCTGTTACAACTAGTACACCTGGTTCAAAGGGTTCAGTTACTTCAGGTGGTTCAGGTGGTTCAGGTGGTTCAGGTGCTACAGTACCTTCA


```

Does this mean that if I replace the ';' that separates the header from the size with a '_', it will serve as the required abundance values for swarm?

Thanks!

**Comment by frederic-mahe** [comment]
@dcastaneda5 you can use swarm with the `-z` option to accept `;size=INTEGER` as abundance values.

**Comment by dcastaneda5** [comment]
That worked! Thanks a lot!
