### ISSUE TITLE
Sort seeds by total mass before output

### ISSUE THREAD

**Issue by torognes** [torognes/swarm#133]
When seeds are written (specified by the `-w`option) to a file, they should be sorted by the total mass of the swarm. If the mass is equal, they should be sorted by the label of the seed.

Remember to add this information to the manual.

**Comment by torognes** [comment]
Code implemented in commit 817778a836e2224ad3e96c825663b41c5471fc8a for swarm3.

**Comment by torognes** [comment]
A note about the output order has been added to the manual in commit f64e4c22dfc6d629c4d9d1efc36904b33b638b98.

**Comment by frederic-mahe** [comment]
OK, this is now covered by tests (see https://github.com/frederic-mahe/swarm-tests/commit/e17aac703910bd6379b12215c9b40930874d7ff1)

**Comment by frederic-mahe** [comment]
Tests to check seed sorting rules when `d > 1` were missing. This has been fixed (see https://github.com/frederic-mahe/swarm-tests/commit/fe1b31f2a4df70fd4c7486230eb7aae9da0562f1)
