### ISSUE TITLE
more amplicons with -d 2 than -d 1?

### ISSUE THREAD

**Issue by KabitaBaral1** [torognes/swarm#150]
Hello,

I was running swarm to detect amplicons on a genotyping project. Luckily, my reads span over the region of interest. However, when I was running -d 1 I was getting a lower number of clusters than -d 2. Would you happen to know why is this? Isn't a -d 1 suppose to give me a higher number of clusters given that I am allowing clustering up to 1 difference?

Thanks,

Kabita Baral

**Comment by frederic-mahe** [comment]
Hi @KabitaBaral1 what you describe is unexpected. The number of clusters should go down as *d* value increases. If you could share with me a sample of your data displaying that behavior and the exact commands you've used, then I could try to find what is happening exactly. Thanks.

**Comment by frederic-mahe** [comment]
@KabitaBaral1 I am going to close that issue. Please feel free to open a new issue if need be.
