### ISSUE TITLE
Get rid of CityHash?

### ISSUE THREAD

**Issue by torognes** [torognes/swarm#152]
I am considering removing the CityHash code from swarm. It is currently only used during dereplication and for checking that FASTA headers are unique. Removing CityHash will make the code smaller and simpler. The CityHash hash function used during dereplication could be replaced with the Zobrist hash function that we use elsewhere (for clustering with d=1). With some modifications the same hash function could also be used on the FASTA headers. I can also optimise the Zobrist hashing code a bit. There will probably be a negligible speed decrease (perhaps 2%) in dereplication time, but dereplication is already extremely fast and limited more by disk reading and writing time than hashing.

**Comment by torognes** [comment]
Implemented in commit d3ca61d32a6b71834638e9da1d32840d7f8fa133.

**Comment by frederic-mahe** [comment]
Nice work, the code is indeed simpler and shorter.

Running cppcheck now reports two style issues in `zobrist.cc` (line 96): scope of `x` could be reduced, and `x` is assigned a value that is never used.

**Comment by torognes** [comment]
Reduced scope of x and initialised it only once now.
