### ISSUE TITLE
macros for min() and max()?

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/swarm#155]
There's a [std::min](https://en.cppreference.com/w/cpp/algorithm/min) and [std::max](https://en.cppreference.com/w/cpp/algorithm/max) in C++. So, could these macros be removed?
```c++
#ifndef MIN
#define MIN(x,y) ((x)<(y)?(x):(y))
#endif

#ifndef MAX
#define MAX(x,y) ((x)>(y)?(x):(y))
#endif
```
or do we need them for systems that do not implement the standard library? (eg.; Microsoft Windows); or because of a conflict between stdlib.h/cstdlib and the STL?

Bjarne Stroustrup recommends to use templates rather than macros, so in our case that would be:
```c++
#ifndef MIN
template<typename T>
inline const T& MIN(const T& x, const T& y)
{
  return (x<y)?x:y;
}
#endif

#ifndef MAX
template<typename T>
inline const T& MAX(const T& x, const T& y)
{
  return (x>y)?x:y;
}
#endif
```

**Comment by torognes** [comment]
It currently fails to compile on some platforms if MIN and MAX are removed.

**Comment by frederic-mahe** [comment]
Is this still the case or can we switch to using std::min and std::max? If not what are the offending platforms?

**Comment by torognes** [comment]
Replaced by `std::min` and `std::max` in commit 0420591b35b18618c5f307e231faca73ee1d2096.
