### ISSUE TITLE
swarm 3.0 on conda

### ISSUE THREAD

**Issue by Gian77** [torognes/swarm#157]
What is the best way to install the last version of SAWRM via conda/bioconda?
Thanks,
G.

**Comment by frederic-mahe** [comment]
the install command should be like that:
```
conda install -c <channel> <package_name>=<version>=<build_string>
```
so, after using
```
conda search -c bioconda swarm
```
the proper command for the latest version of swarm should be:
```
conda install -c bioconda swarm=3.0.0=hc9558a2_0
```

**Comment by Gian77** [comment]
It worked!

I strongly suggest to add an _**how to install using conda/bioconda**_ in the README for people like me running it on a computer cluster instead my own desktop/laptop.

This is what I did:
Activate an environment with Python 3

**`conda activate py3`**

Made sure I have all the channels for the Bioconda packages

**`conda config --add channels defaults`
`conda config --add channels bioconda`
`conda config --add channels conda-forge`**

The installed SWARM 3 using

**`conda install -c bioconda swarm=3.0.0=hc9558a2_0`**

Thanks a lot,

Gian

**Comment by frederic-mahe** [comment]
Thanks @Gian77  I've added a section in the README (see commit 5af96638e5acb9075d16fec126c174b301ceaaa4).
