### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by naurasd** [torognes/swarm#159]
Hi,

trying to install swarm but get the following error when trying to run make:

`make -C src swarm
make[1]: Entering directory 'C:/Users/Nauras/swarm/src'
g++ -g -flto -O3 -march=x86-64 -mtune=generic -std=c++11 -Wall -Wextra  -pedantic   -c -o swarm.o swarm.cc
process_begin: CreateProcess(NULL, g++ -g -flto -O3 -march=x86-64 -mtune=generic -std=c++11 -Wall -Wextra -pedantic -c -o swarm.o swarm.cc, ...) failed.
make (e=2): Das System kann die angegebene Datei nicht finden.
make[1]: *** [<builtin>: swarm.o] Error 2
make[1]: Leaving directory 'C:/Users/Nauras/swarm/src'
make: *** [Makefile:30: bin/swarm] Error 2
`

Any idea what the problem could be?

Cheers
Nauras

**Comment by naurasd** [comment]
Apparently, swarm.o cannot be found. It doesn't exist in the swarm/src directory (swarm.cc does).

**Comment by frederic-mahe** [comment]
Hi @naurasd 

we provide swarm binaries for Windows users, but I think @torognes uses [MinGW](https://en.wikipedia.org/wiki/MinGW) to cross-compile from a GNU/Linux system. So, you might need to modify swarm's Makefile if you want to compile directly on a Windows system. Maybe Torbjørn can comment on that?

**Comment by naurasd** [comment]
Yeah I downloaded the binaries for swarm3.0.0. It was basicaly just a bin folder with swarm.exe. Running this lead to the following:

`Waiting for data... (Hit Ctrl-C and run swarm -h if you meant to read data from a file.)`

What file is needed here?

**Comment by lczech** [comment]
That looks good, so it is running then! Now you need to use the command line to invoke swarm in a way that actually processes data, see the [README](https://github.com/torognes/swarm#launch-swarm).

**Comment by frederic-mahe** [comment]
swarm is waiting for input data, usually a fasta file of dereplicated amplicon sequences. Something like this:
```
>s1_14
ACGTACGT
>s2_2
TCGTACGT
...
```
but slightly different input formats are also possible (see swarm's help).

**Comment by naurasd** [comment]
thanks for the replies, but I am a bit confused. The binary folder contained the exe file. So that means I can run swarm via this file without the need to actually compile it via the make command?

**Comment by torognes** [comment]
Yes, the binary (exe file) is provided for your convenience.

**Comment by naurasd** [comment]
I like the convenient option :-D thanks for the help guys
