### ISSUE TITLE
Link to new swarm 3 paper

### ISSUE THREAD

**Issue by lczech** [torognes/swarm#164]
The documentation still only mentions swarm 1 and 2. Shall we add [swarm 3](https://doi.org/10.1093/bioinformatics/btab493) as well? 

As far as I can tell, the following files are affected:

 - ./CITATION
 - ./README.md
 - ./src/swarm.cc
 - ./man/swarm.1

Any more? If you want, I can prepare a PR for this ;-)

**Comment by torognes** [comment]
Yes! Nice if you could prepare a PR as I am a few days away from my computer.

**Comment by frederic-mahe** [comment]
thanks @lczech ! A PR would be great.

**Comment by lczech** [comment]
Okay, done :-)
