### ISSUE TITLE
Using SWARM on zOTUs instead of dereplicated sequences?

### ISSUE THREAD

**Issue by nick-dil** [torognes/swarm#183]
Hello,

I'm testing SWARM for an eDNA metabarcoding pipeline to see how it performs compared to a "normal" OTU approach with `vsearch`. 

I've tried implementing SWARM as per [Fred's MB pipline](https://github.com/frederic-mahe/swarm/wiki/Fred's-metabarcoding-pipeline). There, SWARM is used to cluster dereplicated sequences with a following chimera removal step on the cluster representative sequences (`-w` seeds).

In the "normal" OTU pipeline we use `vsearch`  and do a denoising step (UNOISE) before clustering (`vsearch --cluster_unoise` + `vsearch --uchime_3denovo`, default options) to generate so-called zero-radius OTUs (zOTUs). I notice that `--cluster_unoise` reduces the number of unique sequences by a lot.

I tried using SWARM with the dereplicated sequences (15M seqs) versus the more cleaned/reduced zOTUs (500k seqs) as input and indeed there is a large difference in number of clusters. In both cases the number of swarm clusters where +-3% of the number of input sequences, a very efficient data reduction! However, the total number of clusters is still a lot higher when using all the dereplicated sequences (even after post-clustering chimera removal). 

My question is:
- Do you think it makes sense to denoise (+remove chimera) before SWARM clustering?

Thanks a lot for your work!
Kind regards,
Nick

PS: I'd also like to ask for some more information on the breaking algorithm implemented in SWARM v2 as I did find little explanation in the paper. Or should I ask this question in another issue?

**Comment by frederic-mahe** [comment]
Hello @nick-dil 

thank you for trying `swarm`!

> Do you think it makes sense to denoise (+remove chimera) before SWARM clustering?

I do not recommend to perform denoising or chimera removal before clustering with swarm. Chimera detection is a slow process and it is more efficient to do it on a smaller number of cluster representatives. If you denoise before using swarm, it will be more difficult for swarm to link similar sequences (like removing stepping stones from a path makes it harder to follow). In practice, it might lead to under-clustering (things that should have been grouped are not).

In my own metabarcoding projects, the final number of clusters is usually not an issue (a few thousand clusters?). Rare clusters have little impact on sample comparison statistics (beta-diversity). If you are concerned about precise alpha-diversity estimates, I suggest to apply additional post-clustering filters:
- remove more rare and weakly assigned clusters maybe?
- use technical replicates and keep only clusters common to all replicates (best solution, but more expensive)

**Comment by frederic-mahe** [comment]
I am closing this issue for now, feel free to re-open if need be.
