### ISSUE TITLE
Check for unique sequences

### ISSUE THREAD

**Issue by torognes** [torognes/swarm#3]
Check if sequences are unique and handle any duplicates; Compute hash of each sequence by MD5, SHA1 or similar

**Comment by frederic-mahe** [comment]
A warning could be issued if some sequences are identical, but I have no idea whether or not this is useful. Getting that information is easy for `d = 1` since swarm hashes the sequences. But it is probably more complex to check for `d > 1`. What do you think @torognes? should we drop that issue?

**Comment by torognes** [comment]
A warning is now issued when duplicated sequences is detected and d>0.
