### ISSUE TITLE
Chimera checking and swarm

### ISSUE THREAD

**Issue by colinbrislawn** [torognes/swarm#43]
When clustering with swarm, when is an appropriate time to check for chimeras?

Developers of previous OTU picking algorithms have recommended chimera checking at different stages. For example, Robert Edgar recommends [using uchime to remove chimeras after OTU picking with uparse](http://drive5.com/usearch/manual/uchime_ref.html). His recommendation is based, in part, on chimera removal heuristics built in to uparse. When using uclust, he recommended referenced-based chimera checking before OTU picking so that OTUs were not influenced by chimeras. 

When using swarm, when and how should we attempt to remove chimeric sequences?

**Comment by frederic-mahe** [comment]
I do it after swarm, on OTU representatives.

I never tested it properly, but the way swarm builds OTUs should not be affected by chimeras. Chimeras will very likely form independent OTUs, it is then logical to check for chimeras after clustering. In practice, you just have to create a fasta file containing OTU representatives (i.e. the most abundant amplicon in each OTU) and run a chimera check on it. As you may already know, uchime needs abundance values to distinguish parents and chimeras, so it is important to keep them. A simple command should do the trick (if your fasta entries are on two lines):
```sh
grep -A 1 -F -f <(cut -d " " -f 1 data.swarms) data.fasta | sed -e '/^--$/d' > data_representatives.fasta
```
Torbjørn has implemented uchime in [vsearch](https://github.com/torognes/vsearch). It is slightly faster and more sensitive than usearch's implementation. I recommend using it.

**Comment by colinbrislawn** [comment]
Hello Frederic,

Thank you for the advice. I'm currently making great use of [vsearch](https://github.com/torognes/vsearch/) and I appreciate how well it integrates with other bioinformatics programs.


I want to make sure I understand the code snippet you sent me:
```bash
grep -A 1 -F -f <(cut -d " " -f 1 data.swarms) data.fasta | sed -e '/^--$/d' > data_representatives.fasta
```
I can see that the inputs are a fasta file and a swarm results file, and the output is a fasta file of representative sequences. Thank you for mentioning that this takes [linearized fasta files](https://github.com/torognes/swarm#linearization). 


Is the output fasta file comparable to the fasta of OTU centroids generated by usearch/vsearch? 
Should the input be my dereplicated fasta file or my seqs before dereplication?
Does this code snippet expect abundance annotations in swarm format or usearch/vsearch format?

Thank you for explaining this to me,
Colin

**Comment by frederic-mahe** [comment]
Hi Colin,

Is the output fasta file comparable to the fasta of OTU centroids generated by usearch/vsearch?

Yes and no. Yes, the output of the code snippet is like a list of usearch centroids. But swarm and uclust (usearch/vsearch) clustering are very different in nature. I personally use swarm to perform clustering for all my amplicon-based projects. Swarm gives higher resolution results and guarantees that each centroid is indeed a local maximum of abundance (more likely to be a "true" sequence). When checking for chimeras, I assume using swarm's centroids will improve the quality of the results.

Should the input be my dereplicated fasta file or my seqs before dereplication?

The dereplicated one, to get the abundance values.

Does this code snippet expect abundance annotations in swarm format or usearch/vsearch format?

The code snippet does not expect abundance annotations per se, but the following step (chimera checking) does.

**Comment by colinbrislawn** [comment]
Hello Frederic,

Thank you for the clarification. I understand how swarm greatly improves the definition of an OTU and provides better biological clusters in both similar and divergent sequences. Swarm introduces some new file types, I'm just having trouble parsing the output. 


I've used the command you provided, but it does not work for me. I ran each command separately and found that the grep command was failing to find any matches in my dereplicated sequences. 

```bash
cut -d " " -f 1 swarm.swarms > cut.swarms
### returns cut.swarms
grep -A 1 -F -f < cut.swarms seqs.derep.fasta > grep_hits.txt
### returns an empty file.
```

Here is what my dereplicated sequence file looks like:
```bash
head seqs.derep.fasta
>515rcbc_JedArch_206_179;size=108822;
TACGGAGGATTCAAGCGTTATCCGGATTTATTGGGTTTAAAGGGTGCGTAGGCGGTCGGATAAGTTAGAGGTGAAATCCC
GAGGCTCAACTTCGGAATTGCCTCTGATACTGTTCGGCTAGAGAGTAGTTGCGGTAGGCGGAATGTATGGTGTAGCGGTG
AAATGCTTAGAGATCATACAGAACACCGATTGCGAAGGCAGCTTACCAAGCTACTTCTGACGTTGAGGCACGAAAGCGTG
GGGAGCAAACAG
>515rcbc_JedArch_173_216;size=70114;
TACGGAGGATCCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGAGCGTAGGTGGATTGTTAAGTCAGTTGTGAAAGTTT
GCGGCTCAACCGTAAAATTGCAGTTGAAACTGGCAGTCTTGAGTACAGTAGAGGTGGGCGGAATTCGTGGTGTAGCGGTG
AAATGCTTAGATATCACGAAGAACTCCGATTGCGAAGGCAGCTCACTGGACTGCAACTGACACTGAGGCTCGAAAGTGTG
GGTATCAAACAG
```
Using the first label as an example, '515rcbc' is the primer, 'JedArch' is the project name, '206' is the sample number, and '179' is the order that sequences appeared in that sample (before dereplication).

Thank you for helping me use swarm for the first time. I'm looking forward to seeing the results!

Colin

**Comment by frederic-mahe** [comment]
Hi Colin,

did you use the parenthesis around the `cut` command?
```
grep -A 1 -F -f <(cut -d " " -f 1 data.swarms) data.fasta | sed -e '/^--$/d' > data_representatives.fasta
```
It tells the shell to redirect the output of `cut` to `grep` as if it was a file (the `-f` option of `grep` normally reads from a file).

**Comment by colinbrislawn** [comment]
When I run the following command, nothing happens.
```bash
grep -A 1 -F -f <(cut -d " " -f 1 swarm.swarms) seqs.derep.fasta
```

**Comment by frederic-mahe** [comment]
OK, can you copy-paste the first 10 lines of the `cut` output? I will compare it to the first lines of your dereplicated fasta file to understand why it is not working.

**Comment by colinbrislawn** [comment]
I didn't think to check the `cut` output. Good idea!

It look like the cut command is not changing my swarm results at all. As an example:
```bash
cut -d " " -f 1 swarm.swarms > cut.swarms
shasum *swarms*
ea44e1201b07bfb02083c30a412f6b9730dbfb9c  cut.swarms
ea44e1201b07bfb02083c30a412f6b9730dbfb9c  swarm.swarms
```
(Would you like me to attach the swarm results somehow? Each line if vary long.)

**Comment by frederic-mahe** [comment]
Hi Colin,

your swarm output should normally contain more than one line. Can you please show me the command line you used to perform the clustering?

**Comment by colinbrislawn** [comment]
Sure!
```bash
	### dereplication
vsearch-1.0.7 --derep_fulllength ../../demultiplexing/split_bc_type_12/seqs.fna \
--output seqs.derep.fasta --sizeout
	
	### clustering with swarm
swarm-2.0.0-osx seqs.derep.fasta -z -t 6 \
-o swarm.swarms -s swarm.stats -u swarm.uc -r swarm.mothur
	### not sure how long (hour?). No .mothur file outputted.
```


The file `seqs.fna` was created with the qiime script [`split_libraries_fastq.py`](http://qiime.org/scripts/split_libraries_fastq.html)

Thanks!
Colin

**Comment by frederic-mahe** [comment]
Hi Colin,

sorry for the late reply, the problem comes from the `-r swarm.mothur` option. That option modifies the swarm's output, and does not create another file. So do not use the `-r` option if you do not intend to use mother formatted results. The `-u` option also slows does swarm a lot, do not use it if you don't really need results in that format.

**Comment by colinbrislawn** [comment]
Hello Frederic,

I was unaware that `-r swarm.mothur` would also change the normal output. I thought it would make a new file, like `-u` does.

I will try again without `-r` and also compare speeds with and without `-u`.

Thank you for all your assistance!
Colin B

**Comment by mdehollander** [comment]
Hi,

I would like to join in on this topic, because i am also working on chimera detection of swarm output. I have a few questions:

- For uchime_denovo does the input need to be in usearch format (with size= in the header)? I have the seqs now formatted as >md5sum_abundance and only the uchime_ref finds chimeras.
- What would be the best way to incorporate the uchime output with the guide to make contigency tables? [Working with several samples](https://github.com/torognes/swarm/wiki/Working%20with%20several%20samples) Just remove chimeric OTUs?

Thanks for any advice!

**Comment by torognes** [comment]
Hi @mdehollander,

Yes, uchime_denovo needs abundance information because by default it will only use a sequence as a potential chimera parent sequence if the abundance of the parent is twice the abundance of the potential chimeric sequence. That level can be adjusted though, with the `--abskew` option. Vsearch does not recognize abundance information in the swarm format (after the underscore).

- Torbjørn

**Comment by frederic-mahe** [comment]
Hi,

(a quick answer, I will take the time to answer fully as soon as I will be available)

if you have swarm-style abundance annotations, you can easily switch to usearch-style annotation:
```
sed -e '/^>/ s/_/;size=/' file.fasta > file2.fasta
```
use `-i` if you want to make the change in place.

**Comment by frederic-mahe** [comment]
Hi @mdehollander,

regarding your second question (how to incorporate chimera detection results in the contingency tables?). What I did recently on my own projects is to perform *de novo* chimera detection on OTU representatives (so, after `swarm`). Using `vsearch`, I obtained a list of chimeras. From there, I see two different possibilities when building the OTU table: 1) discard OTUs whose representative sequence has been identified as a chimera; 2) keep all OTUs but add a "chimeric" column to flag OTUs (0 = not a chimera, 1 = chimera).

The flag option is tempting. It could be interesting to also report the `uchime score` or the 18th column of the `--uchimeout` output. It would allow more subtlety than the binary (chimera or not chimera).

**Comment by frederic-mahe** [comment]
Hi @mdehollander,

> What would be the best way to incorporate the uchime output with the guide to make contigency tables: Working with several samples? Just remove chimeric OTUs?

Yes, my advice is to tag and ultimately remove OTUs identified as chimeras. I will not modify the guide to make contigency tables ([Working with several samples](https://github.com/torognes/swarm/wiki/Working%20with%20several%20samples)) to take chimeras into account. I posted this script as an example of code to build an OTU table, it was not meant to be a comprehensive tool.

I've created a [FAQ](https://github.com/torognes/swarm/wiki/Frequently-Asked-Questions) on swarm's wiki and added a question about chimeras. I will close that issue, feel free to reopen it if you still have questions.

**Comment by olar785** [comment]
Hi,
I would be very keen to use swarm clustering algorithm and just as colinbrislawn I am using vsearch to look for chimeras. My sequences are all about 450bp long but when after swarm clustering and using the command you proposed above: 

grep -A 1 -F -f <(cut -d " " -f 1 data.swarms) data.fasta | sed -e '/^--$/d' > data_representatives.fasta

I end up with "OTUs" of 80bp. Any idea why this is happening? Thanks for your help.

<img width="1216" alt="screen shot 2016-10-13 at 5 26 35 pm" src="https://cloud.githubusercontent.com/assets/20408813/19336784/d1ed8c0c-916a-11e6-8506-46e25c8ff399.png">

<img width="1100" alt="screen shot 2016-10-13 at 5 25 36 pm" src="https://cloud.githubusercontent.com/assets/20408813/19336796/dd243f6c-916a-11e6-8e1e-87cc29ae7f3b.png">

**Comment by tobiasgf** [comment]
Maybe you need to linearize your sequences first, so that there are no line breaks in the sequences? (see the "Swarm front page" here for an "awk" command doing that.)

**Comment by olar785** [comment]
Thanks tobiasgf, it did the trick. I thought my sequences were linearised already as they all seemed to be on one line but apparently not...thanks again!

**Comment by Seena1** [comment]
I performed Swarming and I got 2 files representative.fasta and data.swarms files, I would like to perform VSEARCH, could anyone please help with the command.

**Comment by torognes** [comment]
@Seena1, you could try this command:

`vsearch --uchime_denovo representative.fasta --nonchimeras nonchimeras.fasta`
