### ISSUE TITLE
Rewrite search8.cc and search16.cc using intrinsics for portability

### ISSUE THREAD

**Issue by torognes** [torognes/swarm#44]
Registers xmm8-15 and r8-15 are unavailble on 32-bit platforms. Rewrite with intrinsics to avoid problem.

**Comment by torognes** [comment]
Or use https://github.com/RonnySoak/libssa

**Comment by torognes** [comment]
I do think we should spend time on support for 32-bit systems.

**Comment by torognes** [comment]
Rewrite using intrinsics should perhaps be done anyway. Especially in order to port to other systems as described in issue #107. Could be based on the vsearch code.

**Comment by frederic-mahe** [comment]
Let's reopen the issue under a new title.

**Comment by torognes** [comment]
In the zobrist branch, the SIMD assembly code in search8.cc and search16.cc is now replaced by intrinsics for x86_64. Ready for porting to other architectures (#107).

**Comment by frederic-mahe** [comment]
Great! Let's close the issue then.
