### ISSUE TITLE
Use swarm for dereplication (-d 0)

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/swarm#48]
Rohit Kolora suggested to add a possibility to run swarm with `-d 0` to dereplicate datasets.

The recommended tool for dereplication is `vsearch --derep_full`. Implementing an efficient dereplication in swarm is not a priority for us, and would lead to code duplication. Although, it should be possible to implement some sort of (inefficient but functional) dereplication, just by keeping the present code and allowing the use of `d` values ranging from zero to 255. I guess the fastest way is to use the alternative algorithm (so the branching would be alternative algorithm for `d = 0 or 1`, normal algorithm for higher `d` values).

It seems that users spontaneously try to run `swarm -d 0`. It has some logic to it, so we might as well try to make it possible (if it is not time consuming).

**Comment by torognes** [comment]
Good idea. Not difficult to implement and a nice convenience for users.

**Comment by torognes** [comment]
Implemented in SWARM 2.0.5.
