### ISSUE TITLE
Galaxy wrapper for Swarm

### ISSUE THREAD

**Issue by torognes** [torognes/swarm#50]

**Comment by frederic-mahe** [comment]
There is a team in Toulouse (France) that is working on that. They created a Galaxy wrapper for swarm and they should make it available by the end of March 2015.

**Comment by frederic-mahe** [comment]
The pipeline has been released Yesterday. It is named [FROGS](https://github.com/geraldinepascal/FROGS), and it is a [Galaxy](https://galaxyproject.org/)/CLI workflow designed to produce an OTU count matrix from high depth sequencing amplicon data. FROGS relies on swarm for the clustering phase.
