### ISSUE TITLE
Improve documentation of Fastidious option

### ISSUE THREAD

**Issue by colinbrislawn** [torognes/swarm#52]
I'm excited for the release of swarm 2.1.0 and the new options. I have a questions about `-f` fastidious. 

The documentation mentioned that it reduces the number of small OTUs and provides a way of defining what is 'small' using `-b`, but I'm interested in learning exactly what this algorithm does.

Original fastidious issue: torognes/swarm#42

**Comment by torognes** [comment]
In brief, the fastidious option works as follows: Clusters are first formed as usual in the initial phase with d=1 (single mutation). The mass of each cluster is then calculated as the sum of the abundances of all amplicons in the cluster. The clusters are divided into heavy and light clusters. By default heavy clusters are those having a mass of 3 or more (can be adjusted by the -b or --boundary option), while light clusters have mass less than 3. The light clusters will then be connected to a heavy cluster if their minimum distance is 2 (two mutations). In effect, light clusters (singletons and clusters of mass 2) will be included in a nearby cluster even if the distance is 2. So the results will be closer to what you would get if you specified d=2. The nice thing is that time complexity is linear even with the fastidious option, but it needs a lot of memory (can be controlled by --ceiling) and about 3x the time.

**Comment by colinbrislawn** [comment]
Excellent explanation! Thank you @torognes

**Comment by frederic-mahe** [comment]
Hi @colinbrislawn , I've added a [figure](https://github.com/torognes/swarm#refine-swarm-otus) describing what the fastidious algorithm is doing.

**Comment by colinbrislawn** [comment]
Oh that figure is perfect! It looks like I asked the question just as you were answering it. Sorry for any confusion.
