### ISSUE TITLE
Minor inconsistencies with fastidious

### ISSUE THREAD

**Issue by torognes** [torognes/swarm#53]

**Comment by frederic-mahe** [comment]
We observed a very small difference (0,00005%) in the number of OTUs obtained on the same dataset by two independent runs. We are investigating and running additional tests to try to identify the source of that unexpected variability.

**Comment by torognes** [comment]
I've been able to partially reproduce the problem with a much smaller dataset. When the number of bits for each entry in the Bloom filter is reduced substantially the number of graft candidates may go up slightly (but in the case tested the number of grafts did not increase).

**Comment by torognes** [comment]
It seems like not all sequence variants are generated during the fastidious phase, specifically insertions at the end of the sequence may be missing. This might be the cause.

**Comment by torognes** [comment]
Fixed in 2.1.1.
