### ISSUE TITLE
Clustering with d = 1 and replicates

### ISSUE THREAD

**Issue by robertmueller** [torognes/swarm#56]
Hi,
there seems to be a problem when using swarm with d = 1 on data containing replicates:
swarm (I used version 2.1.1) somehow detects a difference between these exactly matching sequences.

You can check this with the following toy example:

Input FASTA file:
```
>seq1_1 desc1
atggaggtaa
>seq2_1 desc2
atggatgtaa
>seq3_1 desc3
atggaggtaa
```
Using swarm with d = 1 (no other non-I/O-options used) I get the following internal structure output:
```
seq1	seq2		1	1	1
seq1	seq3		1	1	1
```
Changing to d = 2 yields the correct output (provided an exact match is still considered as one 'step' in the OTU):
```
seq1	seq2		1	1	1
seq1	seq3		0	1	1
```
The problem also occurs for 'partly dereplicated' data, i.e. when the replicates have abundances larger than one.

Kind regards,
Robert

**Comment by frederic-mahe** [comment]
Thank you for reporting that issue,

the algorithm used for `d = 1` is different than the one used for `d > 1`. And indeed, the function that creates the `internal-structure` file when `d = 1` does not handle situations where the number of differences is null. We will try to correct that bug soon.

**Comment by frederic-mahe** [comment]
That problem is also described in [issue 55](https://github.com/torognes/swarm/issues/55).

**Comment by torognes** [comment]
You are right. Swarm currently assumes that the input is already dereplicated, at least when d=1. If this is not true the results may be incorrect. Will fix this in next version. May need to always perform a dereplication step before any other processing.

**Comment by torognes** [comment]
I wonder if we should always initially perform an exact dereplication on the sequence before further processing. Even though this specified as a requirement for the input, it seems that it is sometimes forgotten. Dereplication is very fast anyway. We do already perform a similar check on the headers/id's of sequences. What do you think @frederic-mahe ?

**Comment by torognes** [comment]
I'll add a check that all input sequences are unique (that they have been dereplicated) in the next version. See issue #65.

**Comment by torognes** [comment]
Fixed. Added a warning for duplicated sequences and corrected the difference value (column 3) in the structure file for duplicates when d=1.
