### ISSUE TITLE
Sequence identifiers format,  abundace annotation not found error

### ISSUE THREAD

**Issue by jenspreem** [torognes/swarm#57]
From Swarm manual pdf. v1.2.19 released October 3, 2014
Version 1.2.19 fixes a problem related to abundance information when the sequence iden-
tifier includes multiple underscore characters.

No-where else in manuals or -h printout is anything mentioned that input fasta should have sequence headers conforming to any standard. As I'm inputing a fasta file I will get Error: Abundance annotation not found for 106167 sequences.
So it seems that every sequence should have a header that has info on it's abundance? 

From manual:
To speed up the clustering process, strictly identical amplicons should be merged. This step is not mandatory, but it is an important time saver, especially for highly redundant high-throughput sequencing results. 

 Swarm can perform a dereplication for you (with options -d 0 -w), or you can use standard command line tools:

So will the dereplication command in swarm output fasta file that will be correctly formatted with the abundance annotation? 
It might be good to make a mention of the needed format of fasta files to be inputted as someone might want to do their own de-replication with some other tools or use fasta files as they are.

Edit: OK, was foolish and missed the description in pdf. If amplicon identifiers end with
a "_" followed by a positive integer, that value is used as the amplicon copy number in the statistics outputfile .
Can close the issue.

**Comment by frederic-mahe** [comment]
Hi @jenspreem. It also works with `;size=` as a sequenceID and abundance value separator (when using the `-z` option).

**Comment by jenspreem** [comment]
From git readme.
Swarm can perform a dereplication for you (with options |-d 0 -w|),
and from pdf.
When using d = 0, swarm will output results corresponding to a strict 
dereplication of the dataset.

So I tried.

swarm -d 0 -t 4 -w derep.fasta mander.trim.fasta

It also produces Error: Abundance annotation not found for 106167 
sequences and the derep.fasta is an empty file. What did I do wrong?

**Comment by frederic-mahe** [comment]
Yes, swarm can perform a dereplication, but it still assumes your fasta headers are formatted as described in the documentation (`>ampliconID_INTEGER` or `>ampliconID;size=INTEGER[;]`). Dereplication allows you to merge already-correctly formatted datasets, it is not a command you can use to format a dataset.

I modified the documentation to stress out the importance of abundance annotations.
