### ISSUE TITLE
Allow ambiguous bases?

### ISSUE THREAD

**Issue by psathyrella** [torognes/swarm#58]
So I suggest this with some guilt, as implementing ambiguous nucleotides in some of our stuff is a rather fresh and painful memory... but it'd be really cool if `swarm` allowed Ns. I'll have to stick to `vsearch` for the moment otherwise. Is there any chance of getting this?

thanks!

**Comment by frederic-mahe** [comment]
Hi @psathyrella,

Hum, implementing ambiguous nucleotides would imply a major slow down for swarm.

Maybe there is a workaround. If you work with high-throughput sequencing I think you can only get the following nucleotides A, C, G, T or N (where N means unknown). It would not be absurd to arbitrarily replace Ns with another nucleotides. Normally, sequences with Ns are in minority and swarm should automatically graft them to their "true" full sequence (without Ns), without any incidence on the clustering process.

So, a simple command might solve your problem:
```
sed -i '/^>/ ! s/N/A/g' sequences.fasta
```
What do you think? You could give it a try and track the headers of N-containing amplicons to check in which cluster they end up? i would be very interested to here about the results.

**Comment by matsen** [comment]
Thanks for your very speedy response, @frederic-mahe ! 

I think that a danger of doing what you suggest is that if there are areas that are more likely to have Ns than others, these will lead to false grouping of sequences with those N's. If we replace N's with random nucleotides, we will artificially repel sequences with N's. 

Given this, do you think that swarm with this modification would be more accurate than vsearch clustering without?

**Comment by frederic-mahe** [comment]
Hi @matsen,

You are right, **if** Ns tend to appear in the same regions, there is a risk of artificial grouping/splitting. However, it seems to me that Ns are distributed rather randomly. Additionally, swarm produces high-resolution clustering results (when using `d = 1`), that should counter-balance the false grouping effect you describe (but not an eventual false splitting effect)..

I just tried to check the distribution of Ns in an amplicon file (one MiSeq run, 8,506,430 reads), but the number of reads containing Ns is too small to conclude (only 6 reads). I would need to try it on more fastq files.

> Given this, do you think that swarm with this modification would be more accurate than vsearch clustering without?

Yes, I think swarm should yield more accurate results than a clustering based on a global threshold, even when replacing Ns with arbitrary nucleotides.

**Comment by colinbrislawn** [comment]
>I just tried to check the distribution of Ns in an amplicon file (one MiSeq run, 8,506,430 reads), but the number of reads containing Ns is too small to conclude (only 6 reads). I would need to try it on more fastq files.

This has been my experience too; N's are vanishingly rare especially after pairing / quality filtering reads. Because of their rarity, excluding sequences with N's is totally fine.

@matsen, where are you finding all these N's anyway?

**Comment by psathyrella** [comment]
Ok, thanks for the thoughts. You're right that we don't see large numbers of inhomogenous Ns in real data, so in practice, I think we can live with replacing with arbitrary bases (we can't exclude sequences with Ns because some of our data sets are small enough that folks have somewhat emotional attachments to individual sequences).

It would still be rad, though, if the long-term plan included N handling. At least in our (HMM-ey) stuff, all the time we were replacing Ns with arbitrary bases there was just a baseline level of nervousness, since that's the sort of loose arbitrary end that can really come back to bite you when you least expect it.

**Comment by frederic-mahe** [comment]
I would be difficult to deal with ambiguous nucleotides without dramatically slowing the algorithm. In the long term, one possibility though would be to deal with sequences with Ns before the clustering, during the dereplication step.

Sequences with Ns could be put aside and dealt with once non-ambiguous sequences have been dereplicated. For a given sequence with an ambiguous position, all four possibilities are produce. If one of the product matches a non-ambiguous sequence, the abundance of the non-ambiguous sequence is incremented. If more than one product matches a non-ambiguous sequence, then the abundance of the most abundant of the non-ambiguous sequences is incremented.

At the end of the process, ambiguous sequences are discarded, whether or not they matched a non-ambiguous sequence.

In my opinion, that's a safe way to salvage some of the information contained in the ambiguous sequences. I don't think it makes any sense to try to maintain sequences with Ns beyond that point.

**Comment by matsen** [comment]
Thanks, @frederic-mahe, for your thoughtful response.

As far as @psathyrella and I are concerned, you can close this issue.
