### ISSUE TITLE
dereplicating pooled specimens

### ISSUE THREAD

**Issue by nhoffman** [torognes/swarm#61]
Hello,

I'm wondering if there is a recommended approach for dereplication and clustering of reads in pooled specimens. Here's the specific problem I'm trying to address (forgive me for the extremely long comment, but it takes a bit of work to fully specify the problem). Before dereplication/clustering, mapping of reads to specimens is trivial: consider a minimal case of two specimens (S1, S2), each represented by some number of reads (R) that can be assigned to various taxa (T). We wouldn't know the taxon assignments until later, but we can imagine that we do. Here's a representation of such a data set:

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="left" />

<col  class="left" />

<col  class="right" />

<col  class="left" />
</colgroup>
<thead>
<tr>
<th scope="col" class="left">read</th>
<th scope="col" class="left">specimen</th>
<th scope="col" class="right">abundance</th>
<th scope="col" class="left">taxon</th>
</tr>
</thead>

<tbody>
<tr>
<td class="left">R1</td>
<td class="left">S1</td>
<td class="right">1</td>
<td class="left">T1</td>
</tr>

<tr>
<td class="left">R2</td>
<td class="left">S1</td>
<td class="right">1</td>
<td class="left">T1</td>
</tr>

<tr>
<td class="left">R3</td>
<td class="left">S1</td>
<td class="right">1</td>
<td class="left">T2</td>
</tr>

<tr>
<td class="left">R4</td>
<td class="left">S2</td>
<td class="right">1</td>
<td class="left">T3</td>
</tr>

<tr>
<td class="left">R5</td>
<td class="left">S2</td>
<td class="right">1</td>
<td class="left">T3</td>
</tr>

<tr>
<td class="left">R6</td>
<td class="left">S2</td>
<td class="right">1</td>
<td class="left">T1</td>
</tr>
</tbody>
</table>

A trivial grouping operation can be used to generate a taxon table from this data.

Now we cluster or dereplicate within each specimen. We learn that R1 and R2 cluster together, and R4 and R5 cluster together. R1 and R4 are chosen as representatives.

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="left" />

<col  class="left" />

<col  class="right" />

<col  class="left" />
</colgroup>
<thead>
<tr>
<th scope="col" class="left">read</th>
<th scope="col" class="left">specimen</th>
<th scope="col" class="right">abundance</th>
<th scope="col" class="left">taxon</th>
</tr>
</thead>

<tbody>
<tr>
<td class="left">R1</td>
<td class="left">S1</td>
<td class="right">2</td>
<td class="left">T1</td>
</tr>

<tr>
<td class="left">R3</td>
<td class="left">S1</td>
<td class="right">1</td>
<td class="left">T2</td>
</tr>

<tr>
<td class="left">R4</td>
<td class="left">S2</td>
<td class="right">2</td>
<td class="left">T3</td>
</tr>

<tr>
<td class="left">R6</td>
<td class="left">S2</td>
<td class="right">1</td>
<td class="left">T1</td>
</tr>
</tbody>
</table>

It's still easy to generate a taxon table at this point by grouping on (specimen, taxon) and calculating group sums of abundance.

Now we want to pool the per-specimen representatives and dereplicate/cluster again. R1 and R6 cluster together, and R1 is chosen as a representative.

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="left" />

<col  class="left" />

<col  class="right" />

<col  class="left" />
</colgroup>
<thead>
<tr>
<th scope="col" class="left">read</th>
<th scope="col" class="left">specimen</th>
<th scope="col" class="right">abundance</th>
<th scope="col" class="left">taxon</th>
</tr>
</thead>

<tbody>
<tr>
<td class="left">R1</td>
<td class="left">S1</td>
<td class="right">3</td>
<td class="left">T1</td>
</tr>

<tr>
<td class="left">R3</td>
<td class="left">S1</td>
<td class="right">1</td>
<td class="left">T2</td>
</tr>

<tr>
<td class="left">R4</td>
<td class="left">S2</td>
<td class="right">2</td>
<td class="left">T3</td>
</tr>
</tbody>
</table>

Uh, oh - now we've lost the information that T1 (represented by R6) was found in S1 with an abundance of 1. There is no longer a straightforward way to produce a taxon table from information in this table - we'd have to work backward to a previous step to understand where R6 went.

pplacer solves this problem with an abundance annotation format that allows us to preserve references to reads representing each specimen (see <http://matsen.github.io/pplacer/generated_rst/guppy_redup.html#guppy-redup>). The above data set would be represented after pooled dereplication/clustering as follows:

"abundances"

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="left" />

<col  class="left" />

<col  class="right" />
</colgroup>
<thead>
<tr>
<th scope="col" class="left">r_pooled</th>
<th scope="col" class="left">r_orig</th>
<th scope="col" class="right">abundance</th>
</tr>
</thead>

<tbody>
<tr>
<td class="left">R1</td>
<td class="left">R1</td>
<td class="right">2</td>
</tr>

<tr>
<td class="left">R1</td>
<td class="left">R6</td>
<td class="right">1</td>
</tr>

<tr>
<td class="left">R3</td>
<td class="left">R3</td>
<td class="right">1</td>
</tr>

<tr>
<td class="left">R4</td>
<td class="left">R4</td>
<td class="right">2</td>
</tr>
</tbody>
</table>

And in a separate table:

"specimen_map"

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="left" />

<col  class="left" />
</colgroup>
<thead>
<tr>
<th scope="col" class="left">r_orig</th>
<th scope="col" class="left">specimen</th>
</tr>
</thead>

<tbody>
<tr>
<td class="left">R1</td>
<td class="left">S1</td>
</tr>

<tr>
<td class="left">R6</td>
<td class="left">S2</td>
</tr>

<tr>
<td class="left">R3</td>
<td class="left">S1</td>
</tr>

<tr>
<td class="left">R4</td>
<td class="left">S2</td>
</tr>
</tbody>
</table>

Later on, we classify only the reads remaining after the pooled de-replication:

"assignments"

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="left" />

<col  class="left" />
</colgroup>
<thead>
<tr>
<th scope="col" class="left">r_pooled</th>
<th scope="col" class="left">taxon</th>
</tr>
</thead>

<tbody>
<tr>
<td class="left">R1</td>
<td class="left">T1</td>
</tr>

<tr>
<td class="left">R3</td>
<td class="left">T2</td>
</tr>

<tr>
<td class="left">R4</td>
<td class="left">T3</td>
</tr>
</tbody>
</table>

This representation has the following properties:

-   we only need to keep and classify R1, R3, R4
-   the sum of column 3 in abundances.csv is equal to the total number of reads before dereplication/clustering
-   given taxonomic assignments for R1, R3, R4, a taxon table can be calculated by joining these three tables. For example:

    select specimen, taxon, sum(abundance) as read_count
    from abundances join specimen_map using (r_orig)
    join assignments using(r_pooled)
    group by specimen, taxon;

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="left" />

<col  class="left" />

<col  class="right" />
</colgroup>
<thead>
<tr>
<th scope="col" class="left">specimen</th>
<th scope="col" class="left">taxon</th>
<th scope="col" class="right">read_count</th>
</tr>
</thead>

<tbody>
<tr>
<td class="left">S1</td>
<td class="left">T1</td>
<td class="right">2</td>
</tr>

<tr>
<td class="left">S1</td>
<td class="left">T2</td>
<td class="right">1</td>
</tr>

<tr>
<td class="left">S2</td>
<td class="left">T1</td>
<td class="right">1</td>
</tr>

<tr>
<td class="left">S2</td>
<td class="left">T3</td>
<td class="right">2</td>
</tr>
</tbody>
</table>

In the pplacer pipeline, a python script (<http://matsen.github.io/pplacer/scripts.html#deduplicate-sequences>) produces the "abundances" table given a fasta file and "specimen_map" as inputs.

So, finally, my question: how can I perform an equivalent operation using vsearch + swarm for dereplication and clustering for pooled specimens? If necessary, I can write something to produce the above representation of the clustered data, but first I'd like to find out if there is an obvious solution that you can recommend.

Thanks a lot,
Noah

**Comment by colinbrislawn** [comment]
Hello Noah,

>There is no longer a straightforward way to produce a taxon table from information in this table - we'd have to work backward to a previous step to understand where R6 went

I have a straightforward way, but you might not like it:
Map your original reads to your final OTU centroids using vsearch.

`vsearch -usearch_global input_seqs.fna -db rep_set.fna -strand plus -id 0.97 -uc otu_table.map.uc`
Then parse your .uc output into a abundance table.

In my method, R6 would get matched to S1, and the final abundance of S1 (and its abundance in each sample) can be created from .uc file of mapping results.

---

There is a major caveat here: This method works great for clustering with vsearch / usearch / uclust because they all rely on a set threshold. For example, 97%. This is totally not a good fit for swarm given it's different definition of an OTU. 

Also, this is not really my method. This is the method used and promoted by Robert Edgar, the maker of usearch. Take a look at how he describes [mapping reads to OTUs](http://www.drive5.com/usearch/manual/mapreadstootus.html) as part of his [current pipeline](http://www.drive5.com/usearch/manual/uparse_pipeline.html).


---


I'm looking forward to @frederic-mahe's response to this one. I know he values non-huristic, consistent, methods, the the Edgar approach is not a good fit for swarm.

**Comment by nhoffman** [comment]
Hi Colin - thanks for the information, but you're right, I'm not crazy about this approach. Seems like this is a problem most cleanly solved with some careful annotation and bookkeeping, since all of the information is readily available in intermediate files.

**Comment by colinbrislawn** [comment]
Hello hoffman,

I want to reiterate that approach was designed for clustering methods with a fixed similarity threshold, and that it's not an appropriate method for Swarm. (I believe it **is** a good solution for vsearch / usearch.)

Keep in mind that @frederic-mahe does show how to [build an abundance table from Swarm results](https://github.com/torognes/swarm/wiki/Working%20with%20several%20samples).
Have you tried that? Does that approach not work for you?

**Comment by nhoffman** [comment]
Hi @colinbrislawn - looks like I should have read the README more carefully! This question is indeed directly addressed right there. Ultimately I will need the representation of the data that I described above for my pplacer classification pipeline. When I implement a script that produces it, I'll post a link here in case anyone else is planning on combining these tools.

@torognes - I suppose this question may be better titled "how can I use pplacer to classify pooled specimens clustered with swarm" and it seems unlikely to be something that you can answer! Feel free to close if there's nothing else to add.

**Comment by torognes** [comment]
OK, thanks.

**Comment by nhoffman** [comment]
Hello @torognes - just in case any pplacer users find their way to this thread, I thought I'd post a link to the script I wound up writing to use swarm along with pplacer: https://github.com/nhoffman/swarmwrapper

It became somewhat more elaborate than I planned, but it does succeed in greatly simplifying my pipeline code by reducing multiple steps that are typically performed (removing sequences with ambiguities, dereplication, pooling, clustering, and dropping singletons) into a single command.

Once I figured out a specimen pooling strategy, the swarm + pplacer combo has worked out really well for me thus far - thanks!

**Comment by colinbrislawn** [comment]
This is super cool! I qiime does something similar with a much older version of swarm, so I'm glad you got this working with the current version.

Thanks for posting this. If I have questions about your method, can I ask you?

**Comment by nhoffman** [comment]
@colinbrislawn - of course! I'd be grateful for any comments or suggestions.

**Comment by torognes** [comment]
@nhoffman Great! Nice to see that Swarm can be useful for many users.
