### ISSUE TITLE
digits transposed in file name of 2.1.5 binary

### ISSUE THREAD

**Issue by nhoffman** [torognes/swarm#64]
see https://github.com/torognes/swarm/releases - eg, https://github.com/torognes/swarm/releases/download/v2.1.5/swarm-1.2.5-linux-x86_64

Not a big deal, just a bit confusing!

**Comment by torognes** [comment]
Thanks for reporting this error. Sorry for the confusion! Fixed the names of the binaries now. The version numbers in the latest commits are also wrong, but I cannot do much about it. Added a comment about it though.
