### ISSUE TITLE
Check that all input sequences are unique

### ISSUE THREAD

**Issue by torognes** [torognes/swarm#65]
Complain if dereplication has not been performed.

**Comment by frederic-mahe** [comment]
Now that we have `d = 0`, maybe a simple warning should be enough:
```
warning: duplicated sequences detected.
Please consider dereplicating your data to get optimal results from swarm.
```

**Comment by torognes** [comment]
A warning similar to that above (but including the number of duplicated sequences) is now issued when duplicated sequences is detected and d>0.
