### ISSUE TITLE
;size=INT not being accepted

### ISSUE THREAD

**Issue by jpearl01** [torognes/swarm#70]
Hello,
I was just trying to run swarm on a dataset that I've previously dereplicated, the headers look like so:
`>m150110_000356_42168_c100739892550000001823144606051581_s1_p0/46661/ccs;barcodelabel=10_1_H_3119;ee=0.42;size=53`
however, when I run the swarm command:
`swarm -f -t 15 -w OTU_representatives.fasta all_ee1_oriented_filtered_derep_sorted.fasta --statistics-file swarm_stats > /dev/null`
I get this output/error:
```
Swarm 2.1.6 [Feb  8 2016 14:55:35]
Copyright (C) 2012-2015 Torbjorn Rognes and Frederic Mahe
https://github.com/torognes/swarm

Please cite: Mahe F, Rognes T, Quince C, de Vargas C, Dunthorn M (2014)
Swarm: robust and fast clustering method for amplicon-based studies.
PeerJ 2:e593 https://dx.doi.org/10.7717/peerj.593

CPU features:      mmx sse sse2 sse3 ssse3 sse4.1 sse4.2 popcnt avx
Database file:     all_ee1_oriented_filtered_derep_sorted.fasta
Output file:       (stdout)
Statistics file:   swarm_stats
Resolution (d):    1
Threads:           15
Scores:            match: 5, mismatch: -4
Gap penalties:     opening: 12, extension: 4
Converted costs:   mismatch: 9, gap opening: 12, gap extension: 7
Break OTUs:        Yes
Fastidious:        Yes, with boundary 3

Reading database:  100%
Indexing database: 100%
Error: Abundance annotations not found for 161551 sequences, starting on line 1.
Fasta headers must end with abundance annotations (_INT or ;size=INT)
Abundance annotations can be produced by dereplicating the sequences
```

I'm not sure why it doesn't recognize the size annotation in the header, does it have something to do with having multiple ';'?  

~josh

**Comment by frederic-mahe** [comment]
Dear @jpearl01,

swarm does not recognize `;size=INT` annotations by default (maybe we will change that in swarm 3.0). You have to use the `-z` option.

Let me know if it doesn't work or if you encounter other issues.

**Comment by jpearl01** [comment]
Wonderful, thanks!  Appears to be running without problems now.
