### ISSUE TITLE
Remove pairwise alignment settings from when using d =1

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/swarm#75]
When running swarm, the pairwise alignment settings are printed. That could be misleading for users, as `d = 1` does not perform pairwise alignments.
```
Scores:            match: 5, mismatch: -4
Gap penalties:     opening: 12, extension: 4
Converted costs:   mismatch: 9, gap opening: 12, gap extension: 7
```
Ideally, these lines should not appear when using `d = 1`.

**Comment by torognes** [comment]
Fixed in 2.1.8.
