### ISSUE TITLE
Sanitize input options

### ISSUE THREAD

**Issue by torognes** [torognes/swarm#77]
Check option values in more detail for valid ranges. Check illegal or nonsense combinations. Give good warning or error messages.

**Comment by frederic-mahe** [comment]
This is important for the fastidious options. The fastidious step can start after several hours of computation, so it is better to fail immediately if a parameter is out-of-range.

**Comment by torognes** [comment]
Added warning if `-c` or `--ceiling` option specified without `-f` or `--fastidious`.

**Comment by frederic-mahe** [comment]
Perfect. Implemented in swarm 2.1.13
