### ISSUE TITLE
In rare cases Swarm does not terminate properly

### ISSUE THREAD

**Issue by torognes** [torognes/swarm#78]
Under certain rare circumstances it seems like Swarm does not terminate properly even though clustering is finished. It seems to wait/sleep forever for some reason. It is possibly related to glitches in the termination of processing threads. The problem is elusive and difficult to reproduce.

**Comment by frederic-mahe** [comment]
That problem was not observed again. Another code modification may have corrected the bug as a side-effect. I'll close that issue.

**Comment by torognes** [comment]
Probably related to issue #110 just fixed in Swarm version 2.2.2.
