### ISSUE TITLE
Segmentation fault on empty sequences

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/swarm#79]
Continuing my work to build a test suite for swarm, I encountered a segmentation fault:

```
echo -e ">a_10\n" | swarm
```

It is similar to the [issue 171](https://github.com/torognes/vsearch/issues/171) in vsearch.

I don't know how we should deal with empty sequences. Error message and exit? Or should we accept an empty sequence? The easiest and safest way is probably to exit with an error message.

**Comment by torognes** [comment]
Added check for empty sequences. Exits with fatal error if found.

**Comment by frederic-mahe** [comment]
implemented in swarm 2.1.13
