### ISSUE TITLE
Change output sequences to upper case

### ISSUE THREAD

**Issue by torognes** [torognes/swarm#82]
A user reported an annoyance with Swarm outputting symbols in lower case letters, as it was incompatible with `usearch -utax`. I guess it is the seeds file that is being used. USEARCH generally uses lower case letters to indicate masked symbols. We should consider changing the symbols to upper case or leave them as they were in the input.

**Comment by frederic-mahe** [comment]
I agree, output should be in upper case.

When I use `vsearch` to dereplicate a set of amplicons, I use `--relabel_sha1` which converts the sequence to upper case before the digest is computed. So, in my case, swarm receives upper case and outputs lower case sequences (not-matching their digests anymore).

**Comment by frederic-mahe** [comment]
Maybe that change should be published as `swarm 2.2.0` as it may break some user pipelines? It is possible that someone relies on the fact that swarm always output lowercase. If we change the minor version number, the changelog is more likely to be read.

**Comment by torognes** [comment]
Fixed.
