### ISSUE TITLE
Function fatal() declared twice

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/swarm#85]
I was checking the return status if SSE2 is not available and I noticed that the `fatal()` function is defined twice in `util.cc`:
```C
void fatal(const char * msg)
{
  fprintf(stderr, "\nError: %s\n", msg);
  exit(1);
}

void fatal(const char * format, const char * message)
{
  fprintf(stderr, "\n");
  fprintf(stderr, format, message);
  fprintf(stderr, "\n");
  exit(1);
}
```

**Comment by frederic-mahe** [comment]
That's the same thing in vsearch. Maybe that's a normal thing?

**Comment by torognes** [comment]
Yes, it is perfectly ok. They are two different functions with the same name, but different number of arguments. The correct function is selected based on the number and types of arguments.

**Comment by frederic-mahe** [comment]
Thanks, I didn't know this was possible.
