### ISSUE TITLE
Put the cluster seed identifier in the --seeds output

### ISSUE THREAD

**Issue by a1an77** [torognes/swarm#92]
I noticed the output of the --seeds option does not output any sequence identifier for the cluster representatives. It would be very useful to have such and identifier for backtracking purposes and to couple the sequence back to the "cluster representative" identifier.

example output:
>_20
tacggg....
>_10
ggcggg...

Desired ouput:
>cluster_rep_idA_20
tacggg....
>cluster_rep_idB_10
ggcggg...

In the meantime I assume the only way to get the identifier is to rely on the fact that the seeds file has exactly the same order of the cluster file (main output) and the two can be read pairwise one record after the other. Is the assumption correct?

**Comment by frederic-mahe** [comment]
Hi @a1an77 

swarm normally outputs sequence identifiers for the cluster representatives. Maybe there is a problem with your identifiers? could you please paste some of the identifiers you use?

Thanks,

**Comment by frederic-mahe** [comment]
I am going to assume this was a problem with @a1an77 's data. I am closing that issue.
