### ISSUE TITLE
Why is U replaced by T when outputting the seeds

### ISSUE THREAD

**Issue by a1an77** [torognes/swarm#93]
Just noticed that when producing the seeds output all U are replaced by T. Even though for clustering purposes they are equivalent, why not keep the original format?

**Comment by colinbrislawn** [comment]
I think this is related to the grown phase of the swarm, which uses an exact hashing algorithm to recruit variants to the swarm with `d=1` differences from the swarm centroid. While an alignment algorithm could use a scoring matrix to show that U == T, the hashing employed by swarm works better by using only T for the database, queries, and output centroids.

**Comment by frederic-mahe** [comment]
Each U is converted to a T internally when loading the sequences in memory. Keeping track of wether or not some sequences contain "U"s would require some major rewriting of swarm's core. Could you please give us some details? do you have mix sequences using both U and T? 

If all your sequences have "U"s, then it is trivial to convert swarm's fasta output:
```sh
sed -i '/^>/! y/U/T/' rep.fasta
```
